// Code generated by goyacc -l -o parser.go parser.y. DO NOT EDIT.
package parser

import __yyfmt__ "fmt"

import (
	"log"
	"python-obfuscator/pkg/structure"
)

func setResult(lex yyLexer, result structure.Program) {
	lex.(*lexer).result = result
}

type yySymType struct {
	yys                  int
	programComponentList []structure.ProgramComponent
	programComponent     structure.ProgramComponent
	stringList           []string
	functionBody         struct {
		Body   []structure.Line
		Return structure.Expr
	}
	exprList []structure.Expr
	str      string
	line     structure.Line
	hack     interface{}
	expr     structure.Expr
	entity   structure.Entity
}

const NAME = 57346
const BREAK = 57347
const DEF = 57348
const RETURN = 57349
const TAB = 57350

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NAME",
	"','",
	"'('",
	"')'",
	"':'",
	"'\\''",
	"'='",
	"BREAK",
	"DEF",
	"RETURN",
	"TAB",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 54

var yyAct = [...]int{
	4, 6, 41, 31, 19, 27, 47, 40, 8, 2,
	8, 45, 38, 11, 10, 20, 20, 44, 5, 23,
	15, 16, 13, 9, 22, 35, 14, 34, 30, 21,
	20, 26, 13, 33, 17, 32, 28, 36, 29, 37,
	39, 42, 25, 12, 7, 18, 20, 43, 42, 46,
	48, 24, 3, 1,
}

var yyPact = [...]int{
	6, -1000, 12, 3, 2, 39, -1000, -1000, 16, -1000,
	6, 6, 28, 20, 20, -1000, -1000, 38, 24, 31,
	-1000, 34, 26, -1000, 21, 30, -1000, -1000, 20, 18,
	17, -1000, 33, 31, -1000, 1, 30, -1000, -7, -1000,
	4, -1000, 0, -1000, 20, -8, -1000, 4, -1000,
}

var yyPgo = [...]int{
	0, 53, 9, 52, 51, 3, 2, 47, 0, 1,
	45, 5, 44, 4,
}

var yyR1 = [...]int{
	0, 1, 1, 2, 2, 2, 3, 4, 4, 5,
	5, 6, 6, 6, 7, 8, 8, 9, 10, 10,
	11, 11, 12, 13, 13, 13,
}

var yyR2 = [...]int{
	0, 2, 1, 3, 3, 0, 9, 2, 0, 3,
	0, 4, 1, 0, 2, 1, 1, 4, 2, 0,
	3, 0, 3, 1, 3, 1,
}

var yyChk = [...]int{
	-1000, -1, -2, -3, -8, 12, -9, -12, 4, 11,
	11, 11, 4, 6, 10, -2, -2, 6, -10, -13,
	-9, 9, 4, -13, -4, 4, 7, -11, 5, 4,
	7, -5, 5, -13, 9, 8, 4, -11, 11, -5,
	14, -6, -8, -7, 13, 11, -13, 14, -6,
}

var yyDef = [...]int{
	5, -2, 2, 0, 0, 0, 15, 16, 0, 1,
	5, 5, 0, 19, 0, 3, 4, 8, 0, 21,
	23, 0, 25, 22, 0, 10, 17, 18, 0, 0,
	0, 7, 0, 21, 24, 0, 10, 20, 0, 9,
	13, 6, 0, 12, 0, 0, 14, 13, 11,
}

var yyTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 9,
	6, 7, 3, 3, 5, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 8, 3,
	3, 10,
}

var yyTok2 = [...]int{
	2, 3, 4, 11, 12, 13, 14,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("setting result of File")
			}
			reverse(yyDollar[1].programComponentList)
			setResult(yylex, structure.Program{Content: yyDollar[1].programComponentList})
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("setting result of File")
			}
			reverse(yyDollar[1].programComponentList)
			setResult(yylex, structure.Program{Content: yyDollar[1].programComponentList})
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("appending Function to Program")
			}
			yyVAL.programComponentList = append(yyDollar[3].programComponentList, yyDollar[1].programComponent)
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("appending Line to Program")
			}
			yyVAL.programComponentList = append(yyDollar[3].programComponentList, yyDollar[1].entity)
		}
	case 5:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("empty Program")
			}
			yyVAL.programComponentList = []structure.ProgramComponent{}
		}
	case 6:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("parsing Function")
			}
			reverse(yyDollar[4].stringList)
			reverse(yyDollar[9].functionBody.Body)
			yyVAL.programComponent = &structure.Function{
				Name:   yyDollar[2].str,
				Args:   yyDollar[4].stringList,
				Body:   yyDollar[9].functionBody.Body,
				Return: yyDollar[9].functionBody.Return,
			}
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("parsing Args")
			}
			yyVAL.stringList = append(yyDollar[2].stringList, yyDollar[1].str)
		}
	case 8:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("empty Args")
			}
			yyVAL.stringList = []string{}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("parsing Tail")
			}
			yyVAL.stringList = append(yyDollar[3].stringList, yyDollar[2].str)
		}
	case 10:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("empty Tail")
			}
			yyVAL.stringList = []string{}
		}
	case 11:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.functionBody = struct {
				Body   []structure.Line
				Return structure.Expr
			}{Body: append(yyDollar[4].functionBody.Body, yyDollar[1].entity), Return: yyDollar[4].functionBody.Return}
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.functionBody = struct {
				Body   []structure.Line
				Return structure.Expr
			}{Body: []structure.Line{}, Return: yyDollar[1].expr}
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.functionBody = struct {
				Body   []structure.Line
				Return structure.Expr
			}{Body: []structure.Line{}, Return: nil}
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("parsing FunctionCall into Line")
			}
			yyVAL.entity = yyDollar[1].expr
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("parsing Assignment into Line")
			}
			yyVAL.entity = yyDollar[1].line
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("parsing FunctionCall")
			}
			reverse(yyDollar[3].exprList)
			yyVAL.expr = &structure.FunctionCall{Name: yyDollar[1].str, Args: yyDollar[3].exprList}
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("parsing ArgsExpr")
			}
			yyVAL.exprList = append(yyDollar[2].exprList, yyDollar[1].expr)
		}
	case 19:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("empty ArgsExpr")
			}
			yyVAL.exprList = []structure.Expr{}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("parsing TailExpr")
			}
			yyVAL.exprList = append(yyDollar[3].exprList, yyDollar[2].expr)
		}
	case 21:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("empty TailExpr")
			}
			yyVAL.exprList = []structure.Expr{}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("parsing Assignment")
			}
			yyVAL.line = &structure.Assignment{Name: yyDollar[1].str, Assignee: yyDollar[3].expr}
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("parsing FunctionCall into Expr")
			}
			yyVAL.expr = yyDollar[1].expr
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("parsing Constant into Expr")
			}
			yyVAL.expr = &structure.Constant{Content: yyDollar[2].str}
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if yyDebug > 0 {
				log.Println("parsing Name into Expr")
			}
			yyVAL.expr = &structure.Name{Name: yyDollar[1].str}
		}
	}
	goto yystack /* stack new state and value */
}
